name: Sync SOAR and Git

on:
  push:
    branches:
      - main
      - qua

jobs:
  sync_soar_with_git:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python requirements
        run: pip install -r utils/requirements.txt

      - name: Retrieve Playbook and Custom Function Details from Git
        id: get_git_data
        run: |
          PLAYBOOKS=$(find . -maxdepth 1 -name '*.json' -printf '%P\n')
          CUSTOM_FUNCTIONS=$(find ./custom_functions -name '*.json' -printf '%P\n')
          echo "::set-output name=playbooks::$PLAYBOOKS"
          echo "::set-output name=custom_functions::$CUSTOM_FUNCTIONS"

      - name: Sync SOAR with Git Repository
        run: |
          python3 utils/soar_sync.py --playbooks "${{ steps.get_git_data.outputs.playbooks }}" --custom_functions "${{ steps.get_git_data.outputs.custom_functions }}" --api_url "$DEST_API_URL" --api_token "$DEST_API_TOKEN"
