name: Splunk SOAR publish and delete

on:
  push:
    branches:
      - qua
      - main

jobs:
  soar_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout previous commit
        run: git checkout HEAD^1

      - name: Get deleted files
        id: deleted_files
        run: |
          DELETED_FILES=$(git diff --name-only --diff-filter=D ${{ github.sha }})
          PLAYBOOK_AND_CF_FILES=$(echo "$DELETED_FILES" | grep -E '(\.json|\.py)$' | grep -E '(playbooks|custom_functions)/')
          if [ -z "$PLAYBOOK_AND_CF_FILES" ]; then
            echo "No relevant playbook or custom function files were deleted."
            echo "::set-output name=list::"
          else
            echo "::set-output name=list::$PLAYBOOK_AND_CF_FILES"
          fi

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python requirements
        run: pip install -r utils/requirements.txt

      # Existing steps to package and publish objects...

      - name: Handle deleted playbooks and custom functions
        if: steps.deleted_files.outputs.list != ''
        run: |
          IFS=' ' read -ra FILES <<< "${{ steps.deleted_files.outputs.list }}"
          for file in "${FILES[@]}"; do
              if [[ "$file" == *".json" ]]; then
                  object_type="playbook" if [[ "$file" == *"playbooks/"* ]]; then object_type="custom_function"; fi
                  base_name="${file%.json}"
                  python_file="${base_name}.py"
                  if [[ ! -f "$python_file" ]]; then  # Ensure the corresponding Python file does not exist
                    echo "Handling deletion for $file"
                    # Extract object name from file path
                    object_name=$(basename "${file%.json}")
                    # Call the Python script to delete the playbook or custom function
                    python3 utils/soar_delete.py --object_name "$object_name" --object_type "$object_type" --dest_target="$DEST_API_URL" --dest_token "$DEST_API_TOKEN"
                  else
                    echo "Skipping deletion as Python file still exists: $python_file"
                  fi
              fi
          done
