name: Sync SOAR and Git for Qualification and Production

on:
  push:
    branches:
      - qua
      - main

jobs:
  sync_soar_with_git:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python requirements
        run: pip install -r utils/requirements.txt

      - name: Sync SOAR with Git Repository
        run: |
          if [ "${{ github.ref }}" == "refs/heads/qua" ]; then
            DEST_API_URL="$SOAR_QUA_DEST_API_URL"
            DEST_API_TOKEN="$SOAR_QUA_DEST_API_TOKEN"
            DEST_SCM_NAME="$SOAR_QUA_DEST_SCM_NAME"
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            DEST_API_URL="$SOAR_PROD_DEST_API_URL"
            DEST_API_TOKEN="$SOAR_PROD_DEST_API_TOKEN"
            DEST_SCM_NAME="$SOAR_PROD_DEST_SCM_NAME"
          else
            echo "Invalid branch. Exiting."
            exit 1
          fi
          python3 utils/sync_soar.py --dest_target "$DEST_API_URL" --dest_token "$DEST_API_TOKEN" --dest_scm_name "$DEST_SCM_NAME" --mode live
        env:
          SOAR_QUA_DEST_API_URL: ${{ vars.SOAR_QUA_DEST_API_URL }}
          SOAR_QUA_DEST_API_TOKEN: ${{ secrets.SOAR_QUA_DEST_API_TOKEN }}
          SOAR_QUA_DEST_SCM_NAME: ${{ vars.SOAR_QUA_DEST_SCM_NAME }}
          SOAR_PROD_DEST_API_URL: ${{ vars.SOAR_PROD_DEST_API_URL }}
          SOAR_PROD_DEST_API_TOKEN: ${{ secrets.PROD_QUA_DEST_API_TOKEN }}
          SOAR_PROD_DEST_SCM_NAME: ${{ vars.SOAR_PROD_DEST_SCM_NAME }}
