name: Sync SOAR and Git for Qualification

on:
  push:
    branches:
      - qua

jobs:
  sync_soar_with_git:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python requirements
        run: pip install -r utils/requirements.txt

      - name: Sync SOAR with Git Repository
        env:
          SOAR_QUA_DEST_API_URL: ${{ vars.SOAR_QUA_DEST_API_URL }}
          SOAR_QUA_DEST_API_TOKEN: ${{ secrets.SOAR_QUA_DEST_API_TOKEN }}
          SOAR_QUA_DEST_SCM_NAME: ${{ vars.SOAR_QUA_DEST_SCM_NAME }}
        run: |
          python3 utils/sync_soar.py --dest_target "$SOAR_QUA_DEST_API_URL" --dest_token "$SOAR_QUA_DEST_API_TOKEN" --dest_scm_name "$SOAR_QUA_DEST_SCM_NAME"
